# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions


name: Build and Deploy Azure Function App - al-objninja

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './azure-function-app' # Unterordner mit der Function App
  NODE_VERSION: '22.x' # Node.js Version f√ºr Build

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies and Build
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip Function App for Deployment
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          zip -r release.zip .
          mv release.zip $GITHUB_WORKSPACE

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: functionapp
          path: release.zip
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: functionapp

      - name: Unzip Artifact
        run: |
          mkdir -p azure-function-app
          unzip release.zip -d azure-function-app
          rm release.zip


      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_06D3D641510E4E34BF06BBB9F1C50CF0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EEE67BB89E13401CB10854DE97AD9BB0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9AE3F6EA01AC478FAAE605F83EF7E865 }}

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: 'diff-objninja-bus' # Name deiner Function App
          slot-name: 'Production'
          package: './azure-function-app'


          








